using UnityEngine;
using DLSample.Framework;
using DLSample.Facility;
using DLSample.Facility.Events;
using DLSample.Gameplay.Behaviours;
using System.Collections.Generic;

namespace DLSample.Gameplay
{
    public class GameplayEntry : MonoBehaviour
    {
        #region InstanceGetter
        private static GameplayEntry _instance;
        public static GameplayEntry Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = FindAnyObjectByType<GameplayEntry>();

                    if (_instance == null)
                    {
                        _instance = new GameObject {
                            name = typeof(GameplayEntry).Name + "_AutoGenerated",
                            hideFlags = HideFlags.HideInHierarchy
                        }.AddComponent<GameplayEntry>();
                    }
                }
                return _instance;
            }
        }
        #endregion

        public EventBus EventBus { get; private set; }
        public ModulesManager ModulesManager { get; private set; }
        public ServiceLocator ServiceLocator { get; private set; }


        private readonly List<GameplayComponentBase> _components = new();

        private bool _initialized = false;
        private bool _disposed = false;

        private void Awake() => OnInit();
        private void Start() => OnStart();
        private void Update() => OnUpdate();
        private void OnDestroy() => OnDispose();

        private void EnterGameplay()
        {
            foreach (var comp in _components)
            {
                comp.OnEnterGameplay();
            }
        }
        private void ExitGameplay(GameplayEventParams.OnExitGameplayMsg msg)
        {
            OnDispose();
        }

        private void OnInit()
        {
            if (_initialized) return;

            EventBus = new EventBus();
            ModulesManager = new ModulesManager();
            ServiceLocator = new ServiceLocator();

            EventBus.Subscribe<GameplayEventParams.OnExitGameplayMsg>(ExitGameplay);

            _instance = this;
            _initialized = true;
        }

        private void OnStart()
        {
            EnterGameplay();
            ModulesManager.Init();
        }

        private void OnUpdate()
        {
            if (_initialized)
            {
                ModulesManager.Update(Time.deltaTime);
            }
        }

        private void OnDispose()
        {
            if (_disposed) return;

            foreach (var comp in _components)
            {
                comp.OnExitGameplay();
            }

            EventBus.Unsubscribe<GameplayEventParams.OnExitGameplayMsg>(ExitGameplay);

            EventBus.Dispose();
            ModulesManager.Dispose();
            ServiceLocator.Dispose();

            _disposed = true;
            _initialized = false;
        }

        #region PublicAPI
        public void RegisterComponent(GameplayComponentBase component)
        {
            _components.Add(component);
        }
        public void UnregisterComponent(GameplayComponentBase component)
        {
            _components.Remove(component);
        }
        #endregion
    }
}
